In [2]:
print('hello')

hello


In [3]:
import numpy as np

In [6]:
x=[[1,2,3],[1,2,3],[1,2,3]]
y=np.array(x)
print(y)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [7]:
x=[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]

In [8]:
x=np.array(x)

In [9]:
x

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])