In [2]:
print('hello')

hello


In [3]:
import numpy as np

In [6]:
x=[[1,2,3],[1,2,3],[1,2,3]]
y=np.array(x)
print(y)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [21]:
x=[[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]]

In [22]:
x=np.array(x)

In [23]:
x

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [24]:
x.max()

27

In [25]:
x.min()

1

In [26]:
x.argmin()

0

In [30]:
x[:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [28]:
x[2:]

array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [31]:
x[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [32]:
x[-1]

array([[19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [33]:
y=x[2]=42

In [34]:
y

42

In [35]:
x

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[42, 42, 42],
        [42, 42, 42],
        [42, 42, 42]]])

In [38]:
y=np.array(y)
y

array(42)

In [39]:
x[x>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 42, 42, 42,
       42, 42, 42, 42, 42, 42])

In [42]:
x[x<5]

array([1, 2, 3, 4])